import './styles.css';
import { supabase } from './supabase.js';

const app=document.querySelector('#app');
let session=null, profile=null, services=[];
const labels={submitted:'تم استلام الطلب',accepted:'تم قبول الطلب',in_progress:'قيد التجهيز',submitted_to_authority:'تم تقديم المعاملة',processing:'قيد المعالجة',ready_for_collection:'جاهز للاستلام',collected:'تم الاستلام',completed:'تم التسليم',cancelled:'ملغى'};
const gov=['بيروت','جبل لبنان','الشمال','عكار','البقاع','بعلبك - الهرمل','الجنوب','النبطية'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>'$'+Number(v||0).toFixed(0);
const go=r=>{location.hash=r==='home'?'':r; render();};
const busy=(b,on,t='جارٍ التنفيذ...')=>{if(!b)return;if(on){b.dataset.old=b.textContent;b.textContent=t;b.disabled=true}else{b.textContent=b.dataset.old||b.textContent;b.disabled=false}};
function toast(m,bad=false){let x=document.querySelector('.toast');if(!x){x=document.createElement('div');x.className='toast';document.body.appendChild(x)}x.textContent=m;x.className='toast show'+(bad?' bad':'');clearTimeout(window.__t);window.__t=setTimeout(()=>x.classList.remove('show'),3000)}
function shell(body){return `<header><button class="brand" data-go="home">عنّك</button><button class="toplink" data-go="${session?'account':'login'}">${session?'حسابي':'دخول'}</button></header><main>${body}</main>`}
async function load(){const {data:{session:s}}=await supabase.auth.getSession();session=s;if(s){const {data}=await supabase.from('profiles').select('*').eq('id',s.user.id).maybeSingle();profile=data}const {data}=await supabase.from('services').select('*').eq('active',true).order('sort_order');services=data||[]}
function home(){return shell(`<section class="hero"><small>معاملات عقارية في لبنان</small><h1>اطلب أوراق عقارك.<br>ونحن نتابعها عنك.</h1><button class="primary" data-go="${session?'new':'login'}">طلب جديد</button>${session?'<button class="ghost" data-go="orders">طلباتي</button>':''}</section>`)}
function login(){return shell(`<section class="card narrow"><h2>دخول</h2><p>سنرسل رابط دخول إلى بريدك.</p><form id="login"><input name="email" type="email" required placeholder="البريد الإلكتروني"><button class="primary full">إرسال الرابط</button></form></section>`)}
function newOrder(){return shell(`<section class="card"><div class="title"><h2>طلب جديد</h2><button data-go="home">رجوع</button></div><form id="order"><div class="grid"><select name="governorate" required><option value="">المحافظة</option>${gov.map(x=>`<option>${x}</option>`).join('')}</select><input name="district" placeholder="القضاء"></div><div class="grid"><input name="cadastral_area" required placeholder="المنطقة العقارية"><input name="property_number" required placeholder="رقم العقار"></div><div class="services">${services.map(s=>`<label><input type="radio" name="service" value="${s.code}" required><span><b>${esc(s.name_ar)}</b><em>${money(s.customer_price)}</em></span></label>`).join('')}</div><input name="name" value="${esc(profile?.full_name)}" placeholder="الاسم"><input name="phone" value="${esc(profile?.phone)}" required placeholder="رقم الهاتف"><textarea name="notes" placeholder="ملاحظة (اختياري)"></textarea><button class="primary full">إرسال الطلب</button></form></section>`)}
async function orders(){const {data,error}=await supabase.from('orders').select('*').eq('customer_id',session.user.id).order('created_at',{ascending:false});if(error)return toast(error.message,true);app.innerHTML=shell(`<section><div class="title"><h2>طلباتي</h2><button data-go="home">رجوع</button></div><div class="stack">${(data||[]).map(o=>`<button class="row" data-order="${o.id}"><span><b>${o.public_code}</b><small>${esc(o.cadastral_area)} • ${esc(o.property_number)}</small></span><i>${labels[o.status]||o.status}</i></button>`).join('')||'<div class="empty">لا يوجد طلبات.</div>'}</div><button class="primary full" data-go="new">طلب جديد</button></section>`);bind()}
async function detail(id,agent=false){const [{data:o,error},{data:e},{data:d},{data:i}]=await Promise.all([supabase.from('orders').select('*').eq('id',id).single(),supabase.from('order_events').select('*').eq('order_id',id).order('created_at'),supabase.from('documents').select('*').eq('order_id',id).order('created_at'),supabase.from('order_items').select('*').eq('order_id',id)]);if(error)return toast(error.message,true);const next={accepted:['in_progress','بدء العمل'],in_progress:['submitted_to_authority','تم تقديم المعاملة'],submitted_to_authority:['processing','قيد المعالجة'],processing:['ready_for_collection','جاهز للاستلام'],ready_for_collection:['collected','تم الاستلام'],collected:['completed','إكمال الطلب']}[o.status];app.innerHTML=shell(`<section class="card"><div class="title"><h2>${o.public_code}</h2><button data-go="${agent?'agent':'orders'}">رجوع</button></div><div class="summary"><b>${esc(o.cadastral_area)} • عقار ${esc(o.property_number)}</b><span>${(i||[]).map(x=>esc(x.service_name_ar)).join('، ')}</span><strong>${money(o.total_amount)}</strong></div><h3>التتبّع</h3><div class="timeline">${(e||[]).map(x=>`<div><b>${esc(x.label_ar)}</b><small>${new Date(x.created_at).toLocaleString('ar-LB')}</small></div>`).join('')}</div>${agent?`<input id="file" type="file" accept=".pdf,image/*"><label class="check"><input id="visible" type="checkbox"> يظهر للعميل</label><button class="secondary full" data-upload="${o.id}">رفع ملف</button>${next?`<button class="primary full" data-status="${next[0]}" data-id="${o.id}">${next[1]}</button>`:''}`:`${(d||[]).filter(x=>x.visible_to_customer).map(x=>`<button class="download full" data-download="${esc(x.storage_path)}">${esc(x.original_name||'فتح المستند')}</button>`).join('')}${o.status==='submitted'?`<button class="danger full" data-cancel="${o.id}">إلغاء الطلب</button>`:''}`}</section>`);bind()}
function account(){return shell(`<section class="card narrow"><div class="title"><h2>حسابي</h2><button data-go="home">رجوع</button></div><form id="profile"><input name="name" value="${esc(profile?.full_name)}" placeholder="الاسم"><input name="phone" value="${esc(profile?.phone)}" placeholder="الهاتف"><button class="primary full">حفظ</button></form>${profile?.role==='customer'?'<button class="secondary full" id="apply">التسجيل كوكيل</button>':''}${profile?.role==='agent'?'<button class="secondary full" data-go="agent">بوابة الوكيل</button>':''}${profile?.role==='admin'?'<button class="secondary full" data-go="admin">الإدارة</button>':''}<button class="ghost full" id="logout">تسجيل الخروج</button></section>`)}
async function agent(){const {data:a}=await supabase.from('agent_profiles').select('*').eq('user_id',session.user.id).maybeSingle();if(!a){app.innerHTML=shell('<section class="card narrow"><h2>بوابة الوكيل</h2><button class="primary full" id="apply">التسجيل كوكيل</button></section>');return bind()}if(a.verification_status!=='approved'){app.innerHTML=shell(`<section class="card narrow"><h2>طلب الوكيل</h2><p>الحالة: <b>${a.verification_status==='pending'?'قيد المراجعة':esc(a.verification_status)}</b></p></section>`);return}const [{data:avail},{data:mine},{data:coverage}]=await Promise.all([supabase.rpc('list_available_orders'),supabase.from('orders').select('*').eq('assigned_agent_id',session.user.id).not('status','in','("completed","cancelled")'),supabase.from('agent_coverage').select('*').eq('agent_id',session.user.id).eq('active',true)]);app.innerHTML=shell(`<section><div class="title"><h2>بوابة الوكيل</h2><label class="check"><input id="avail" type="checkbox" ${a.available?'checked':''}> متاح</label></div><div class="coverage"><form id="coverage"><select name="governorate" required><option value="">منطقة العمل</option>${gov.map(x=>`<option>${x}</option>`).join('')}</select><input name="district" placeholder="القضاء (اختياري)"><button class="secondary">حفظ</button></form><small>${(coverage||[]).length?'مناطقك: '+coverage.map(x=>esc(x.governorate)+(x.district?' / '+esc(x.district):'')).join('، '):'أضف منطقة عمل لتظهر لك الطلبات.'}</small></div><h3>طلباتي</h3><div class="stack">${(mine||[]).map(o=>`<button class="row" data-agent-order="${o.id}"><b>${o.public_code}</b><i>${labels[o.status]}</i></button>`).join('')||'<div class="empty">لا يوجد.</div>'}</div><h3>طلبات متاحة</h3><div class="stack">${(avail||[]).map(o=>`<div class="job"><span><b>${esc(o.service_names)}</b><small>${esc(o.governorate)} • ${esc(o.cadastral_area)}</small></span><strong>${money(o.agent_payout)}</strong><button class="primary" data-accept="${o.id}">قبول</button></div>`).join('')||'<div class="empty">لا يوجد حالياً.</div>'}</div></section>`);bind()}
async function admin(){if(profile?.role!=='admin')return go('home');const [{data:a},{data:s},{data:o}]=await Promise.all([supabase.from('agent_profiles').select('*'),supabase.from('services').select('*').order('sort_order'),supabase.from('orders').select('*').order('created_at',{ascending:false}).limit(50)]);const ids=(a||[]).map(x=>x.user_id);let names={};if(ids.length){const {data:p}=await supabase.from('profiles').select('id,full_name,email').in('id',ids);(p||[]).forEach(x=>names[x.id]=x)}app.innerHTML=shell(`<section><div class="title"><h2>الإدارة</h2><button data-go="home">رجوع</button></div><h3>الوكلاء</h3><div class="stack">${(a||[]).map(x=>`<div class="adminrow"><span><b>${esc(names[x.user_id]?.full_name||names[x.user_id]?.email||x.user_id)}</b><small>${x.verification_status}</small></span>${x.verification_status==='approved'?`<button class="danger" data-suspend="${x.user_id}">تعليق</button>`:`<button class="primary" data-approve="${x.user_id}">اعتماد</button>`}</div>`).join('')||'<div class="empty">لا يوجد.</div>'}</div><h3>الأسعار</h3><div class="stack">${(s||[]).map(x=>`<form class="price" data-service="${x.id}"><b>${esc(x.name_ar)}</b><input name="cp" type="number" value="${x.customer_price}"><input name="ap" type="number" value="${x.agent_payout}"><label class="check"><input name="active" type="checkbox" ${x.active?'checked':''}> فعّال</label><button class="secondary">حفظ</button></form>`).join('')}</div><h3>آخر الطلبات</h3><div class="stack">${(o||[]).map(x=>`<div class="adminrow"><b>${x.public_code}</b><i>${labels[x.status]}</i></div>`).join('')}</div></section>`);bind()}
function render(){if(!session){const r=location.hash.slice(1);app.innerHTML=r==='login'?login():home();return bind()}const r=location.hash.slice(1)||'home';if(r==='new')app.innerHTML=newOrder();else if(r==='account')app.innerHTML=account();else if(r==='orders')return orders();else if(r==='agent')return agent();else if(r==='admin')return admin();else app.innerHTML=home();bind()}
function bind(){
 document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));
 const l=document.querySelector('#login');if(l)l.onsubmit=async e=>{e.preventDefault();const b=l.querySelector('button');busy(b,1);const email=new FormData(l).get('email');const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.href.split('#')[0]}});busy(b,0);error?toast(error.message,1):toast('تم إرسال رابط الدخول')};
 const o=document.querySelector('#order');if(o)o.onsubmit=async e=>{e.preventDefault();const f=new FormData(o),b=o.querySelector('button');busy(b,1);const {error}=await supabase.rpc('create_order',{p_customer_name:f.get('name')||'',p_customer_phone:f.get('phone'),p_customer_email:session.user.email||'',p_governorate:f.get('governorate'),p_district:f.get('district')||'',p_cadastral_area:f.get('cadastral_area'),p_property_number:f.get('property_number'),p_property_section:'',p_notes:f.get('notes')||'',p_service_codes:[f.get('service')]});busy(b,0);error?toast(error.message,1):(toast('تم إرسال الطلب'),go('orders'))};
 const p=document.querySelector('#profile');if(p)p.onsubmit=async e=>{e.preventDefault();const f=new FormData(p),b=p.querySelector('button');busy(b,1);const {error}=await supabase.rpc('update_my_profile',{p_full_name:f.get('name')||'',p_phone:f.get('phone')||'',p_locale:'ar'});busy(b,0);if(error)toast(error.message,1);else{await load();toast('تم الحفظ')}};
 const lo=document.querySelector('#logout');if(lo)lo.onclick=async()=>{await supabase.auth.signOut();profile=null;session=null;go('home')};
 const ap=document.querySelector('#apply');if(ap)ap.onclick=async()=>{busy(ap,1);const {error}=await supabase.rpc('apply_as_agent');busy(ap,0);if(error)toast(error.message,1);else{await load();go('agent')}};
 const av=document.querySelector('#avail');if(av)av.onchange=async()=>{const {error}=await supabase.rpc('set_agent_availability',{p_available:av.checked});if(error){av.checked=!av.checked;toast(error.message,1)}}; const cv=document.querySelector('#coverage');if(cv)cv.onsubmit=async e=>{e.preventDefault();const d=new FormData(cv),b=cv.querySelector('button');busy(b,1);const {error}=await supabase.rpc('replace_agent_coverage',{p_governorate:d.get('governorate'),p_district:d.get('district')||''});busy(b,0);error?toast(error.message,1):(toast('تم حفظ منطقة العمل'),agent())};
 document.querySelectorAll('[data-order]').forEach(x=>x.onclick=()=>detail(x.dataset.order));
 document.querySelectorAll('[data-agent-order]').forEach(x=>x.onclick=()=>detail(x.dataset.agentOrder,true));
 document.querySelectorAll('[data-accept]').forEach(x=>x.onclick=async()=>{busy(x,1);const {error}=await supabase.rpc('accept_order',{p_order_id:x.dataset.accept});error?toast(error.message==='order_unavailable'?'أخذه وكيل آخر':error.message,1):(toast('أصبح الطلب لك'),agent())});
 document.querySelectorAll('[data-status]').forEach(x=>x.onclick=async()=>{busy(x,1);const {error}=await supabase.rpc('update_order_status',{p_order_id:x.dataset.id,p_status:x.dataset.status,p_note:''});error?toast(error.message,1):(toast('تم التحديث'),detail(x.dataset.id,true))});
 document.querySelectorAll('[data-upload]').forEach(x=>x.onclick=async()=>{const f=document.querySelector('#file')?.files?.[0];if(!f)return toast('اختر ملفاً',1);busy(x,1,'جارٍ الرفع...');const path=x.dataset.upload+'/'+crypto.randomUUID()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');const up=await supabase.storage.from('order-files').upload(path,f);if(up.error){busy(x,0);return toast(up.error.message,1)}const {error}=await supabase.from('documents').insert({order_id:x.dataset.upload,kind:'final_document',storage_path:path,original_name:f.name,mime_type:f.type,file_size:f.size,visible_to_customer:document.querySelector('#visible').checked,uploaded_by:session.user.id});busy(x,0);error?toast(error.message,1):toast('تم رفع الملف')});
 document.querySelectorAll('[data-download]').forEach(x=>x.onclick=async()=>{const {data,error}=await supabase.storage.from('order-files').download(x.dataset.download);if(error)return toast(error.message,1);const u=URL.createObjectURL(data);window.open(u,'_blank')});
 document.querySelectorAll('[data-cancel]').forEach(x=>x.onclick=async()=>{if(!confirm('إلغاء الطلب؟'))return;const {error}=await supabase.rpc('cancel_own_order',{p_order_id:x.dataset.cancel});error?toast(error.message,1):go('orders')});
 document.querySelectorAll('[data-approve]').forEach(x=>x.onclick=()=>agentStatus(x.dataset.approve,'approved'));
 document.querySelectorAll('[data-suspend]').forEach(x=>x.onclick=()=>agentStatus(x.dataset.suspend,'suspended'));
 document.querySelectorAll('[data-service]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const d=new FormData(f),b=f.querySelector('button');busy(b,1);const {error}=await supabase.rpc('admin_update_service',{p_service_id:f.dataset.service,p_customer_price:+d.get('cp'),p_agent_payout:+d.get('ap'),p_active:d.get('active')==='on'});busy(b,0);error?toast(error.message,1):toast('تم الحفظ')});
}
async function agentStatus(id,status){const {error}=await supabase.rpc('admin_set_agent_status',{p_agent_id:id,p_status:status});error?toast(error.message,1):admin()}
window.addEventListener('hashchange',render);
supabase.auth.onAuthStateChange(async(_e,s)=>{session=s;profile=null;if(s)await load();render()});
await load();render();
